### ISSUE TITLE
Customising ContactZendeskActivity/ContactZendeskFragment to attach logs automatically

### ISSUE THREAD

**Issue by triveous** [zendesk/sdk_demo_app_android#40]
Great demo, however, I have certain specific requirements like

- I have to attach logs (a zip file) to the issue/ticket when users are trying to open the case, that has to be pre-attached (with the user's permission which I will seek earlier). So they won't always have an option to attach files and they don't have to a) generate the file and b) browse to it.
- I would like to upload the attachment (the zip file) and submit the ticket in the background and then show a notification once it's done
- Ability to attach logs (one click) in the conversation Activity/Fragment in the "My Tickets" section

Can 
- ContactZendeskActivity/ContactZendeskFragment have a static method which has an option to pre-include an attachment in certain workflows
- we upload the attachments and submit the ticket in the background using something like an IntentService, without making the user wait
- Provide similar customisation options in the "My Tickets" section

**Comment by baz8080** [comment]
Hi @triveous 

There are a few things here that would not be possible with the default UI, but could be achievable by using our [API providers](https://developer.zendesk.com/embeddables/docs/android/providers). 

You would use the [UploadProvider](https://zdmobilesdkdocdev.herokuapp.com/android-sdk-providers/com/zendesk/sdk/network/UploadProvider.html) to upload files, and then use the [token from the response](https://zdmobilesdkdocdev.herokuapp.com/android-sdk-providers/) when creating a request with the [RequestProvider](https://zdmobilesdkdocdev.herokuapp.com/android-sdk-providers/)

If you'd like to share you idea for adding this functionality to the SDK, the best place is in one of our Zendesk communities, where it will have a broader reach and discussion. I'd suggest either the [Zendesk SDKs community](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) for feature requests specific to the SDK, or the [Product feedback community](https://support.zendesk.com/hc/en-us/community/topics/200132066-Product-feedback) for more general ideas

**Comment by triveous** [comment]
Thank you, this sounds good, let me take this forward to the SDK community.
