### ISSUE TITLE
DO NOT SHOW category

### ISSUE THREAD

**Issue by anjalisingh** [zendesk/sdk_demo_app_android#44]
Hi, I am following the steps mentioned in https://developer.zendesk.com/embeddables/docs/android/tickets_and_kb to display the help center.

However, I cannot find a way to hide the category names. I only want to show the sections and articles on my activity.

Current hierarchy:

 CATEGORY
    SECTION
       ARTICLE

Expected:

SECTION
       ARTICLE

Is there a way this can be achieved?

**Comment by baz8080** [comment]
hi @anjalisingh. That is not supported. If you wish to customise the UI beyond what our documentation covers you must provide your own UI and use our API providers.
