### ISSUE TITLE
withAndroidStoreRatingButton() is not showing the "Yes, rate our app" button

### ISSUE THREAD

**Issue by swaby** [zendesk/sdk_demo_app_android#8]
I've tried everything to get it to work and it just doesn't seem to want to come up.. Creating my own button came with its own side effects. Is there something I'm forgetting to do? The documentation says:

Redirects user to the Android app listing configured in your Zendesk

I have not configured an app listing in Zendesk.. Do you mean in the Zendesk SDK, or on the website?

**Comment by swaby** [comment]
I also noticed that when I compile and run the sample application on device, the "No, send feedback" button does not come up, but on my application, it does show up..

**Comment by JoelReeves** [comment]
I noticed the positive button missing too. I believe you have to enable the Rate My App feature by going into your Zendesk account's  Mobile SDK section. You'll see a "Rate My App" tab. When you scroll down you'll see a "Android app store link" field. 

When I had this field empty I didn't see the button in the app. After inputting a link to another of my apps on the Play Store I could see the button.

**Comment by swaby** [comment]
@JoelReeves oh I get it. It wasn't something I wasn't doing. I'll get in touch with my Zendesk admin ASAP.

**Comment by JoelReeves** [comment]
No problem. You can see some of the values you can change here
https://developer.zendesk.com/embeddables/docs/android/rate_my_app

Good luck
