### ISSUE TITLE
Send Feedback Dialog crashes app when the home button is pressed

### ISSUE THREAD

**Issue by swaby** [zendesk/sdk_demo_app_android#9]
1. tap "Rate the app"
2. tap "no, send feedback"
3. make sure the "sorry about that" dialog is visible
4. hit the home button

Observe the app crashes as the home screen is presented.
```
java.lang.RuntimeException: Unable to pause activity {xxxxxx.SupportActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.FragmentManager.popBackStack(int, int)' on a null object reference
```

**Comment by JoelReeves** [comment]
I'm receiving a different RunTimeException:

java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.zendesk.sdk.feedback.impl.ZendeskFeedbackConnector)

**Comment by baz8080** [comment]
@swaby Sorry for the delay on this one. It should be fixed in the latest version. Please reopen the issue if it isn't working for you.
